<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LaserCubeSharp.ProtocolChecks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaserCubeSharp\LaserCubeSharp.csproj" />
  </ItemGroup>
</Project>
